# Generated by Django 3.0.2 on 2020-03-14 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
    ]
